version: '3.8'

services:
  queue_bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: queue_bot
    links:
      - "redis:db"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/app/

  redis:
    image: redis:6.0.16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: celery_worker
    image: celery:3.2
    env_file:
      - .env
    volumes:
      - ./src:/app
      - ./celery_data/celery_config:/app/celery_config
      - ./celery_data/celery_logs:/var/log/celery
      - ./celery_data/celery_results:/var/lib/celery/results
    depends_on:
      - queue_bot

volumes:
  redis: