version: '3.8'

services:
  queue_bot:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "redis:db"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/app/

  redis:
    image: redis:6.0.16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

volumes:
  redis: