version: '3.8'

services:
  queue_bot:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "redis:db"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/app/

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - '6378:6378'
    volumes:
      - redis:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis: