FROM redis:6.0.16-alpine

COPY redis.conf /usr/local/etc/redis/redis.conf

RUN chmod 777 -R /data
RUN chmod 777 -R /etc
RUN chmod 777 -R /var

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
