version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
  queuebot:
    build: app
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app/
